# Generated by Django 5.2.5 on 2025-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Phone Mark")),
            ],
            options={
                "verbose_name": "Phone mark",
                "verbose_name_plural": "Phone marks",
            },
        ),
    ]
