# Generated by Django 5.2.5 on 2025-08-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_phonename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonename',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Phone Mark'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='model_name')),
                ('storage', models.IntegerField()),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('release_date', models.DateField()),
                ('price', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('phone_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.phonename')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
