# Generated by Django 5.2.5 on 2025-08-16 08:43

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_phonename_name_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='phonename',
            name='image',
            field=models.ImageField(null=True, upload_to='marks_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
