# Generated by Django 5.2.5 on 2025-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_image_phonename_image_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('messages', models.TextField(verbose_name='messages')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
